version: "3.9"

services:

    ai4-papi-prod:
        image: "ignacioheredia/ai4-papi:prod"
        restart: always
        environment:
            - NOMAD_ADDR=https://193.146.75.205:4646
        volumes:
            - /home/ubuntu/nomad-certs/nomad-prod:/home/nomad-certs
            - /mnt/ai4os-logs/ai4-accounting:/home/ai4-accounting
        ports:
            - 8080:80

    ai4-papi-dev:
    # Right now dev is pointing to same services as prod.
    # Will change in the future.
        image: "ignacioheredia/ai4-papi:prod"
        restart: always
        environment:
            - NOMAD_ADDR=https://193.146.75.205:4646
        volumes:
            - /home/ubuntu/nomad-certs/nomad-prod:/home/nomad-certs
            - /mnt/ai4os-logs/ai4-accounting:/home/ai4-accounting
        ports:
            - 8081:80
